version: "3"
services:
      
  discordBot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node
    image: node:alpine


  voicevox-engine:
    platform: linux/x86_64
    container_name: voicevox-engine
    image: voicevox/voicevox_engine:nvidia-ubuntu20.04-latest
    restart: always
    ports:
      - "50021:50021"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
